version: '3'
services:
    mypoint-postgres:
        image: postgres:11
        container_name: mypoint-postgres
        restart: always
        hostname: mypoint-postgres
        networks:
            - mypoint-network
        environment:
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}

    mypoint-rabbitmq:
        restart: always
        image: rabbitmq:3-management
        container_name: mypoint-rabbitmq
        hostname: mypoint-rabbitmq
        networks:
            - mypoint-network
        ports:
            - 5672:5672
            - 25676:25676
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
networks:
    mypoint-network:
        driver: bridge
